language: node_js
node_js:
  - 8
cache:
  directories:
  - node_modules
before_script:
  - npm prune
script:
  - npm install
  - npm run build
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
after_success:
  - npm run lh -- --perf=90 --a11y=90 --bp=90 https://mattyao-cotd.github.io/lighthouse-react-demo/
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  - LIGHTHOUSE_API_KEY=8447cb0fe3424f2ebd9b41bca77e1404

  